added initial draft for new cli incremental build approach
finos/morphir pull request #101
Opened 2022-05-09 11:41 UTC by nwokafor-choongsaeng

2022-05-09 14:38 UTC, AttilaMihaly requested changes

2022-05-09 14:38 UTC, AttilaMihaly commented on docs/Morphir CLI incremental build approach (ADR format).md
> +# ADR for Morphir CLI incremental build approach
Can you change the name of the file to follow the naming convention like this:
`0002-morphir-cli-incremental-build-approach.md`

2022-12-19 19:46 UTC, stephengoldbaum approved these changes

2023-02-06 09:34 UTC, AttilaMihaly approved these changes

2023-02-06 09:34 UTC, merged